@app_url=http://localhost:5065
@dapr_url=http://localhost:3500

### ------------------------------
### Call the start endpoint of the web app
// @name startRequest
POST {{app_url}}/start
Content-Type: application/json

[
    {
        "Name" : "Alex",
        "GiftType" : "WoodenToy"
    },
    {
        "Name" : "Rene",
        "GiftType" : "Book"
    },
    {
        "Name" : "Robin",
        "GiftType" : "CatalystEarlyAccess"
    }
]

### ------------------------------
### Get the SantaClausWorkflow status via the Dapr API
@instanceId={{startRequest.response.body.*}}
GET {{dapr_url}}/v1.0-beta1/workflows/dapr/{{instanceId}}


### ------------------------------
### Run the SantaClausWorkflow via the Dapr API
###
@workflow_id={{$guid}}

// @name wfrequest
POST {{dapr_url}}/v1.0-beta1/workflows/dapr/SantaClausWorkflow/start?instanceID={{workflow_id}}
Content-Type: application/json

[
    {
        "Name" : "Alex",
        "GiftType" : "WoodenToy"
    },
    {
        "Name" : "Rene",
        "GiftType" : "Book"
    },
    {
        "Name" : "Robin",
        "GiftType" : "CatalystEarlyAccess"
    }
]

### ------------------------------
### Get the SantaClausWorkflow status via the Dapr API
@wfresponse={{wfrequest.response.body.instanceID}}
GET {{dapr_url}}/v1.0-beta1/workflows/dapr/{{wfresponse}}
